title: "Awesome Jekyll Site"
description: "A beautifully designed Jekyll site deployed with GitHub Pages."
baseurl: "" # Leave empty for root
url: "https://deep-security-dev.github.io/awesome-jekyll-site" # Replace with your site's URL
theme: minima # You can replace 'minima' with another theme
author: 
  name: "Samuel Egbuka"
  email: "samuelegbuka.com"
  LinkedIn: "https://www.linkedin.com/in/samuel-egbuka/" # Optional
  github_username: "Egbuka" # Optional

# Social links (Optional)
social_links:
  - name: GitHub
    url: https://github.com/deep-security-dev/awesome-jekyll-site

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
